### ISSUE TITLE
Code #LCIE on Mac

### ISSUE THREAD

**Issue by blanky6739** [Flutterish/rurusetto-addon#10]
When opening osu!lazer 2023.1130.0 on mac, the ruleset didn't load and gave the error #LCIE.

Logs:
[database.log](https://github.com/Flutterish/rurusetto-addon/files/13598215/database.log)
[network.log](https://github.com/Flutterish/rurusetto-addon/files/13598217/network.log)
[performance.log](https://github.com/Flutterish/rurusetto-addon/files/13598218/performance.log)
[runtime.log](https://github.com/Flutterish/rurusetto-addon/files/13598219/runtime.log)

**Comment by Flutterish** [comment]
Thanks for the report. The newest release works.
