### ISSUE TITLE
Currently crashing due to one of the last 2 updates

### ISSUE THREAD

**Issue by TheFantasticLoki** [Flutterish/rurusetto-addon#3]
Please update and thanks in advance for all the work you have put into maintaining this.

**Comment by TheFantasticLoki** [comment]
For those that are currently crashing and need to update all of their rulesets the last Working game version is [2022.205.0](https://github.com/ppy/osu/releases/tag/2022.205.0) for Addon V1.8

**Comment by Flutterish** [comment]
Thanks for letting me know, I've released a fix.

**Comment by TheFantasticLoki** [comment]
Damn that was hella fast thanks so much @Flutterish you're a beast
