### ISSUE TITLE
Addon V1.8.1 Not updating rulesets

### ISSUE THREAD

**Issue by TheFantasticLoki** [Flutterish/rurusetto-addon#4]
Tried to update all my rulesets after updating the addon and after restarting lazer it shows they all still need updated. Tried again with just Touhosu and same thing.

**Comment by Flutterish** [comment]
Did they actually update though or not? This might be an issue with version checking rather than if it works.
Can you try removing them, restarting osu and installing with the addon again?

**Comment by TheFantasticLoki** [comment]
must be version checking issue as Yoso also reports unknown version but that is also a private ruleset so who know
![osu_2022-02-21_18-14-12](https://user-images.githubusercontent.com/26889568/155045513-94c1c1ad-1578-4611-9d75-d10214a914cd.png)
s

**Comment by Flutterish** [comment]
Could you show me the creation and modification date of a public ruleset that shows up as outdated? It should be in properties of its .dll file.

**Comment by Flutterish** [comment]
The yoso thing is definitely a bug though. Ruru does not have information about its versioning.

**Comment by TheFantasticLoki** [comment]
![osu_2022-02-21_18-39-37](https://user-images.githubusercontent.com/26889568/155047602-896af262-2f4f-45a4-919e-8c0467722ba7.png)
![image](https://user-images.githubusercontent.com/26889568/155047655-f209753f-de3f-4adf-b3c2-2e92a5f9dc27.png)

**Comment by Flutterish** [comment]
I think I found the issue in the code. Can you test if [this build](https://drive.google.com/file/d/1uf6xhz5FsLv1Qe2sBtQl5lHcRLXXyUyM/view?usp=sharing) resolves this? I can't test this on my side very quickly because it requires modifying file metadata.

**Comment by TheFantasticLoki** [comment]
Yes this does fix the issue all show as up to date now

**Comment by TheFantasticLoki** [comment]
can you also make another side addon who's only purpose is making sure the rurusetto addon is up to date and if not auto updates it?

**Comment by Flutterish** [comment]
I'm pretty sure its impossible to do since anything that would break one would also break the other. Thoigh, if/when ruru addon gets added to the ruru wiki, you will probably be able to make it update itself

**Comment by TheFantasticLoki** [comment]
well and when it broke before it would still load it would only break after opening the panel so maybe have an update check happen in the background for the addon itself even if you need to code a manual git check and HOPEFULLY it'll survive most issues especially if it's code that is run before anything else

**Comment by Flutterish** [comment]
I think this is a bit out of scope for this issue. I will close this one after I push the fix tomorrow, but if you wish, you can open a discussion (though Im not sure if this repo has discussions enabled, you can make another issue though) about this self-update thing.
